import * as Icons from "lucide-react";

export const iconMap = {
  billing: Icons.CreditCard,
  calendar: Icons.Calendar,
  cancel: Icons.X,
  check: Icons.Check,
  chevronRight: Icons.ChevronRight,
  chevronLeft: Icons.ChevronLeft,
  chevronUp: Icons.ChevronUp,
  chevronDown: Icons.ChevronDown,
  confirm: Icons.Check,
  copy: Icons.Copy,
  dashboard: Icons.LayoutDashboard,
  delete: Icons.Trash2,
  dot: Icons.Circle,
  download: Icons.Download,
  edit: Icons.Pencil,
  editProfile: Icons.UserCog,
  feedback: Icons.Megaphone,
  email: Icons.Mail,
  entry: Icons.FileText,
  entries: Icons.Files,
  eye: Icons.Eye,
  eyeOff: Icons.EyeOff,
  help: Icons.LifeBuoy,
  home: Icons.Home,
  image: Icons.Image,
  info: Icons.Info,
  loading: Icons.Loader2,
  location: Icons.MapPin,
  login: Icons.LogIn,
  logout: Icons.LogOut,
  map: Icons.Map,
  menu: Icons.Menu,
  more: Icons.MoreVerticalIcon,
  newEntry: Icons.FilePlus,
  notifications: Icons.Bell,
  panel: Icons.PanelLeft,
  password: Icons.Lock,
  permissions: Icons.ShieldCheck,
  register: Icons.UserPlus,
  save: Icons.Save,
  search: Icons.Search,
  settings: Icons.Settings,
  share: Icons.Share2,
  success: Icons.CheckCircle2,
  upload: Icons.Upload,
  user: Icons.User,
  userGroup: Icons.Users,
  warning: Icons.AlertTriangle,
} as const;

export type IconName = keyof typeof iconMap;

// This gives a typed array of keys
export const iconNames = Object.keys(iconMap) as IconName[];
