import { ApolloWrapper } from "@/providers/ApolloWrapper";
import { LocaleLayout } from "@/providers/LocaleLayout";
import { NextAuthSessionProvider } from "@/providers/NextAuthSessionProvider";
import "@voyagr/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

interface RootLayoutProps {
  children: ReactNode;
  params: { locale: string };
}
export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body
        className={`${inter.className} w-screen max-h-screen overflow-hidden`}
      >
        <NextAuthSessionProvider>
          <LocaleLayout params={{ locale }}>
            <ApolloWrapper>{children}</ApolloWrapper>
          </LocaleLayout>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
