import { ApolloWrapper } from "@/components/providers/ApolloWrapper";
import { NextAuthSessionProvider } from "@/components/providers/NextAuthSessionProvider";
import "@voyagr/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
